name: Code Check
on:
  workflow_call:

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ESLint, TypeScript, Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download deps
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint:strict

      - name: Type check
        run: bun run typecheck

      - name: Prettier check
        run: bun run prettier:format
